[package]
name = "ruffle_gc"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "1.2"
generational-arena = "0.2.8"
once_cell = "1.7"
ruffle_gc_derive = { path = "../ruffle_gc_derive" }

[dev-dependencies]
trybuild = "1.0"
